controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


app_resultat:
    path: /resultat
    controller: App\Controller\ResultatController::index


app_registration:
    path: /register
    controller: App\Controller\RegistrationController::index

